// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpaViyhsIGbifi45k0TQP7TtyAhib8Pyw',
    appId: '1:1027642031520:web:42154899ba68831a0578c5',
    messagingSenderId: '1027642031520',
    projectId: 'flash-chat-v2-2e8d0',
    authDomain: 'flash-chat-v2-2e8d0.firebaseapp.com',
    storageBucket: 'flash-chat-v2-2e8d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1vn6bhF55DRuxgwsbO9HBhY0Lnl2tbc',
    appId: '1:1027642031520:android:19bf89ebd5ebe0980578c5',
    messagingSenderId: '1027642031520',
    projectId: 'flash-chat-v2-2e8d0',
    storageBucket: 'flash-chat-v2-2e8d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwU1L1-xFf3b0rdTWQff4dMV-JpNrRdOA',
    appId: '1:1027642031520:ios:baccbad56ed0e3e60578c5',
    messagingSenderId: '1027642031520',
    projectId: 'flash-chat-v2-2e8d0',
    storageBucket: 'flash-chat-v2-2e8d0.appspot.com',
    iosClientId: '1027642031520-aunqtn3ev2rgjfd1tutvnirvpa8fr0kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwU1L1-xFf3b0rdTWQff4dMV-JpNrRdOA',
    appId: '1:1027642031520:ios:492b352a03ed0cfa0578c5',
    messagingSenderId: '1027642031520',
    projectId: 'flash-chat-v2-2e8d0',
    storageBucket: 'flash-chat-v2-2e8d0.appspot.com',
    iosClientId: '1027642031520-1u1omnscqa5tsc7an6gs05n25h472agc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatV2.RunnerTests',
  );
}
